/* 
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Caplinked.Api;
using Caplinked.Model;
using Caplinked.Client;
using System.Reflection;

namespace Caplinked.Test
{
    /// <summary>
    ///  Class for testing Activity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActivityTests
    {
        // TODO uncomment below to declare an instance variable for Activity
        //private Activity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Activity
            //instance = new Activity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Activity
        /// </summary>
        [Test]
        public void ActivityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Activity
            //Assert.IsInstanceOfType<Activity> (instance, "variable 'instance' is a Activity");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'WorkspaceId'
        /// </summary>
        [Test]
        public void WorkspaceIdTest()
        {
            // TODO unit test for the property 'WorkspaceId'
        }
        /// <summary>
        /// Test the property 'Verb'
        /// </summary>
        [Test]
        public void VerbTest()
        {
            // TODO unit test for the property 'Verb'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'SubjectType'
        /// </summary>
        [Test]
        public void SubjectTypeTest()
        {
            // TODO unit test for the property 'SubjectType'
        }
        /// <summary>
        /// Test the property 'SubjectId'
        /// </summary>
        [Test]
        public void SubjectIdTest()
        {
            // TODO unit test for the property 'SubjectId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
