/* 
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Caplinked.Api;
using Caplinked.Model;
using Caplinked.Client;
using System.Reflection;

namespace Caplinked.Test
{
    /// <summary>
    ///  Class for testing CustomWatermarkSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomWatermarkSettingTests
    {
        // TODO uncomment below to declare an instance variable for CustomWatermarkSetting
        //private CustomWatermarkSetting instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomWatermarkSetting
            //instance = new CustomWatermarkSetting();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomWatermarkSetting
        /// </summary>
        [Test]
        public void CustomWatermarkSettingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomWatermarkSetting
            //Assert.IsInstanceOfType<CustomWatermarkSetting> (instance, "variable 'instance' is a CustomWatermarkSetting");
        }

        /// <summary>
        /// Test the property 'WatermarkId'
        /// </summary>
        [Test]
        public void WatermarkIdTest()
        {
            // TODO unit test for the property 'WatermarkId'
        }
        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Test]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'CustomText'
        /// </summary>
        [Test]
        public void CustomTextTest()
        {
            // TODO unit test for the property 'CustomText'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Opacity'
        /// </summary>
        [Test]
        public void OpacityTest()
        {
            // TODO unit test for the property 'Opacity'
        }
        /// <summary>
        /// Test the property 'FontSize'
        /// </summary>
        [Test]
        public void FontSizeTest()
        {
            // TODO unit test for the property 'FontSize'
        }
        /// <summary>
        /// Test the property 'Rotation'
        /// </summary>
        [Test]
        public void RotationTest()
        {
            // TODO unit test for the property 'Rotation'
        }
        /// <summary>
        /// Test the property 'Hposition'
        /// </summary>
        [Test]
        public void HpositionTest()
        {
            // TODO unit test for the property 'Hposition'
        }
        /// <summary>
        /// Test the property 'Vposition'
        /// </summary>
        [Test]
        public void VpositionTest()
        {
            // TODO unit test for the property 'Vposition'
        }
        /// <summary>
        /// Test the property 'DisplayUserName'
        /// </summary>
        [Test]
        public void DisplayUserNameTest()
        {
            // TODO unit test for the property 'DisplayUserName'
        }
        /// <summary>
        /// Test the property 'DisplayUserEmail'
        /// </summary>
        [Test]
        public void DisplayUserEmailTest()
        {
            // TODO unit test for the property 'DisplayUserEmail'
        }
        /// <summary>
        /// Test the property 'DisplayIpAddress'
        /// </summary>
        [Test]
        public void DisplayIpAddressTest()
        {
            // TODO unit test for the property 'DisplayIpAddress'
        }
        /// <summary>
        /// Test the property 'DisplayTime'
        /// </summary>
        [Test]
        public void DisplayTimeTest()
        {
            // TODO unit test for the property 'DisplayTime'
        }
        /// <summary>
        /// Test the property 'DisplayWorkspaceName'
        /// </summary>
        [Test]
        public void DisplayWorkspaceNameTest()
        {
            // TODO unit test for the property 'DisplayWorkspaceName'
        }

    }

}
