/* 
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Caplinked.Api;
using Caplinked.Model;
using Caplinked.Client;
using System.Reflection;

namespace Caplinked.Test
{
    /// <summary>
    ///  Class for testing ExpiringUrl
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExpiringUrlTests
    {
        // TODO uncomment below to declare an instance variable for ExpiringUrl
        //private ExpiringUrl instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExpiringUrl
            //instance = new ExpiringUrl();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExpiringUrl
        /// </summary>
        [Test]
        public void ExpiringUrlInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExpiringUrl
            //Assert.IsInstanceOfType<ExpiringUrl> (instance, "variable 'instance' is a ExpiringUrl");
        }

        /// <summary>
        /// Test the property '_ExpiringUrl'
        /// </summary>
        [Test]
        public void _ExpiringUrlTest()
        {
            // TODO unit test for the property '_ExpiringUrl'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

    }

}
