/* 
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Caplinked.Api;
using Caplinked.Model;
using Caplinked.Client;
using System.Reflection;

namespace Caplinked.Test
{
    /// <summary>
    ///  Class for testing FileViewerImage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileViewerImageTests
    {
        // TODO uncomment below to declare an instance variable for FileViewerImage
        //private FileViewerImage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileViewerImage
            //instance = new FileViewerImage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileViewerImage
        /// </summary>
        [Test]
        public void FileViewerImageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileViewerImage
            //Assert.IsInstanceOfType<FileViewerImage> (instance, "variable 'instance' is a FileViewerImage");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Test]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'ExpiringUrl'
        /// </summary>
        [Test]
        public void ExpiringUrlTest()
        {
            // TODO unit test for the property 'ExpiringUrl'
        }
        /// <summary>
        /// Test the property 'ExpiringThumbnailUrl'
        /// </summary>
        [Test]
        public void ExpiringThumbnailUrlTest()
        {
            // TODO unit test for the property 'ExpiringThumbnailUrl'
        }

    }

}
