/* 
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Caplinked.Api;
using Caplinked.Model;
using Caplinked.Client;
using System.Reflection;

namespace Caplinked.Test
{
    /// <summary>
    ///  Class for testing FolderContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FolderContentTests
    {
        // TODO uncomment below to declare an instance variable for FolderContent
        //private FolderContent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FolderContent
            //instance = new FolderContent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FolderContent
        /// </summary>
        [Test]
        public void FolderContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FolderContent
            //Assert.IsInstanceOfType<FolderContent> (instance, "variable 'instance' is a FolderContent");
        }

        /// <summary>
        /// Test the property 'Folder'
        /// </summary>
        [Test]
        public void FolderTest()
        {
            // TODO unit test for the property 'Folder'
        }
        /// <summary>
        /// Test the property 'ImmediateSubfolders'
        /// </summary>
        [Test]
        public void ImmediateSubfoldersTest()
        {
            // TODO unit test for the property 'ImmediateSubfolders'
        }
        /// <summary>
        /// Test the property 'ImmediateSubfiles'
        /// </summary>
        [Test]
        public void ImmediateSubfilesTest()
        {
            // TODO unit test for the property 'ImmediateSubfiles'
        }

    }

}
