/* 
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Caplinked.Api;
using Caplinked.Model;
using Caplinked.Client;
using System.Reflection;

namespace Caplinked.Test
{
    /// <summary>
    ///  Class for testing SupportInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SupportInformationTests
    {
        // TODO uncomment below to declare an instance variable for SupportInformation
        //private SupportInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SupportInformation
            //instance = new SupportInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SupportInformation
        /// </summary>
        [Test]
        public void SupportInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SupportInformation
            //Assert.IsInstanceOfType<SupportInformation> (instance, "variable 'instance' is a SupportInformation");
        }

        /// <summary>
        /// Test the property 'SupportNumber'
        /// </summary>
        [Test]
        public void SupportNumberTest()
        {
            // TODO unit test for the property 'SupportNumber'
        }
        /// <summary>
        /// Test the property 'SupportEmail'
        /// </summary>
        [Test]
        public void SupportEmailTest()
        {
            // TODO unit test for the property 'SupportEmail'
        }
        /// <summary>
        /// Test the property 'SupportWebsite'
        /// </summary>
        [Test]
        public void SupportWebsiteTest()
        {
            // TODO unit test for the property 'SupportWebsite'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
