/* 
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Caplinked.Api;
using Caplinked.Model;
using Caplinked.Client;
using System.Reflection;

namespace Caplinked.Test
{
    /// <summary>
    ///  Class for testing Team
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeamTests
    {
        // TODO uncomment below to declare an instance variable for Team
        //private Team instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Team
            //instance = new Team();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Team
        /// </summary>
        [Test]
        public void TeamInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Team
            //Assert.IsInstanceOfType<Team> (instance, "variable 'instance' is a Team");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TeamOwnerId'
        /// </summary>
        [Test]
        public void TeamOwnerIdTest()
        {
            // TODO unit test for the property 'TeamOwnerId'
        }
        /// <summary>
        /// Test the property 'CreatorId'
        /// </summary>
        [Test]
        public void CreatorIdTest()
        {
            // TODO unit test for the property 'CreatorId'
        }
        /// <summary>
        /// Test the property 'AllowedWorkspaces'
        /// </summary>
        [Test]
        public void AllowedWorkspacesTest()
        {
            // TODO unit test for the property 'AllowedWorkspaces'
        }
        /// <summary>
        /// Test the property 'AllowedAdmins'
        /// </summary>
        [Test]
        public void AllowedAdminsTest()
        {
            // TODO unit test for the property 'AllowedAdmins'
        }
        /// <summary>
        /// Test the property 'DrmEnabled'
        /// </summary>
        [Test]
        public void DrmEnabledTest()
        {
            // TODO unit test for the property 'DrmEnabled'
        }
        /// <summary>
        /// Test the property 'Watermarking'
        /// </summary>
        [Test]
        public void WatermarkingTest()
        {
            // TODO unit test for the property 'Watermarking'
        }
        /// <summary>
        /// Test the property 'SuppressEmails'
        /// </summary>
        [Test]
        public void SuppressEmailsTest()
        {
            // TODO unit test for the property 'SuppressEmails'
        }

    }

}
